server:
  port: 8000
spring:
  application:
    name: cambio-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.17.0.3:3306/cambio_service?useTimezone=true&serverTimeZone=UTC
    username: intellij
    password: myMysqlPassword0502
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  flyway:
    url: jdbc:mysql://172.17.0.3:3306/cambio_service?useTimezone=true&serverTimeZone=UTC
    user: intellij
    password: myMysqlPassword0502
  sleuth:
    sampler:
      probability: 1.0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
springdoc:
  api-docs:
    path: cambio-service/v3/api-docs
  show-actuator: true