version: '3.4'

services:
  zipkin:
    image: openzipkin/zipkin:2.23.2
    ports:
      - "9411:9411"
    networks:
      - microservices-network

  naming-server:
    image: andrew2609/naming-server:0.0.1-SNAPSHOT
    ports:
      - "8761:8761"
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge